Script started on Sat 11 Mar 2017 09:38:29 PM CST
[01;32mariel@ariel-X555LJ[01;34m ~/Desktop/lab1 $[00m g[Kvim question--B.cpp
[?1000h[?1049h[?1h=[2;1H▽[6n[1;1H  [1;1H[1;14r[?12;25h[?12l[?25h[27m[m[H[2J[?25l[14;1H"question--B.cpp" 17L, 198C[>c[1;1H[33m  1 [m[4m[35m#include[m[4m[31m<iostream>[m[4m                                                          [m[2;1H[1m[34m  2 [m[35m#include[m[31m<cstdio>[m
[1m[34m  3 [m[33musing[m [32mnamespace[m std;
[1m[34m  4 
  5 [m[32mint[m main() {
[1m[34m  6 [m  [32mint[m n;
[1m[34m  7 [m  cin>>n;
[1m[34m  8 [m  printf([31m"[m[35m%d[m[31m"[m, n);
[1m[34m  9 [m  [33mwhile[m(n!=[31m1[m) {
[1m[34m 10 [m    [33mif[m(n%[31m2[m==[31m1[m)
[1m[34m 11 [m      n=[31m3[m*n+[31m1[m;
[1m[34m 12 [m    [33melse[m
[1m[34m 13 [m      n/=[31m2[m;[14;63H1,1[11CTop[1;5H[?12l[?25h[?1000l[?1006h[?1002h[?1006l[?1002l[?1006h[?1002hP+q436f\P+q6b75\P+q6b64\P+q6b72\P+q6b6c\P+q2332\P+q2334\P+q2569\P+q2a37\P+q6b31\[?25l[14;1H[K[14;1H:[?12l[?25hw[?25l[?12l[?25hq[?25l[?12l[?25h[?25l[?1006l[?1002l"question--B.cpp" 17L, 198C written
[?1l>[?12l[?25h[?1049l[01;32mariel@ariel-X555LJ[01;34m ~/Desktop/lab1 $[00m vim question--B.cpp[1P question--B.cpp[1P question--B.cpp[1P question--B.cppg question--B.cpp+ question--B.cpp+ question--B.cpp[C question--B.cpp- question--B.cppo question--B.cpp[C question--B.cppq question--B.cppe question--B.cpps question--B.cppt question--B.cppi question--B.cppo question--B.cppn question--B.cpp[1@u[C[C[C[C[C[C- question--B.cpp- question--B.cppB question--B.cpp
[01;32mariel@ariel-X555LJ[01;34m ~/Desktop/lab1 $[00m ./question--B
22
22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1[01;32mariel@ariel-X555LJ[01;34m ~/Desktop/lab1 $[00m git clone https:''[K[K//github.com/ArielWu0203/lab 1.[K[A[01;32mariel@ariel-X555LJ[01;34m ~/Desktop/lab1 $[00m git clone https://github.com/ArielWu0203/lab1.[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cgit
fatal: destination path 'lab1' already exists and is not an empty directory.
[01;32mariel@ariel-X555LJ[01;34m ~/Desktop/lab1 $[00m exit

Script done on Sat 11 Mar 2017 09:41:16 PM CST
